name: Build Binaries on Tag

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          python build.py

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-binaries
          path: dist/**
